[symbols]
# Erstes Symbol: Erste verwendete Hauptdatei; 1 entspricht 01.png.
start_symbol = 1
# Anzahl verwendeter Symbole: -1 verwendet automatisch alle ab start_symbol vorhandenen Symbole.
symbol_count = -1
